### ISSUE TITLE
build project

### ISSUE THREAD

**Issue by Mokhless** [mregni/statistics-for-emby-server#41]
Hi,
I want to build this project in ubuntu for get the file .dll . it's possible?
if possible , please help me

**Comment by mregni** [comment]
You can grab the latest build here: https://emby.media/community/index.php?/topic/35266-new-statistics-plugin/?p=437458 

extract the dll inside the zip file to "/var/lib/emby-server/plugins"

Let me know if it's working for you! When I publish the plugin in the catalog you can install the new updates from there as well.

**Comment by Mokhless** [comment]
thanks , i added plugin but when i select a user for see the statistic , it always loading and nothing show

**Comment by mregni** [comment]
Did you run the background task before going to the plugin page?

If not, go to the tasks screen and run the Statistics task.
